# Generated by Django 3.1.3 on 2021-11-20 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('use_matching', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='MatchingResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mate_list', models.CharField(max_length=1000)),
                ('update_at', models.DateTimeField()),
                ('User', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, related_name='matching_result', to='matching.user')),
            ],
            options={
                'db_table': 'matching_result',
            },
        ),
        migrations.CreateModel(
            name='MatchingInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sex', models.IntegerField()),
                ('age', models.FloatField()),
                ('mbti', models.CharField(max_length=10)),
                ('user_smoking', models.IntegerField()),
                ('mate_smoking', models.FloatField()),
                ('user_pet', models.IntegerField()),
                ('user_pet_dog', models.IntegerField(default=0)),
                ('user_pet_cat', models.IntegerField(default=0)),
                ('user_pet_reptile_fish', models.IntegerField(default=0)),
                ('user_pet_rodent', models.IntegerField(default=0)),
                ('user_pet_bird', models.IntegerField(default=0)),
                ('mate_pet', models.FloatField()),
                ('mate_pet_dog', models.FloatField(default=0)),
                ('mate_pet_cat', models.FloatField(default=0)),
                ('mate_pet_reptile_fish', models.FloatField(default=0)),
                ('mate_pet_rodent', models.FloatField(default=0)),
                ('mate_pet_bird', models.FloatField(default=0)),
                ('air_like_airconditioner', models.FloatField()),
                ('air_like_heater', models.FloatField()),
                ('noise_talking', models.FloatField()),
                ('noise_music', models.FloatField()),
                ('noise_alarm', models.IntegerField()),
                ('user_bug_killer', models.FloatField()),
                ('mate_bug_killer', models.IntegerField()),
                ('user_cooking', models.IntegerField()),
                ('mate_cooking', models.IntegerField()),
                ('eat_together', models.IntegerField()),
                ('share_item', models.FloatField()),
                ('mate_alcohol', models.FloatField()),
                ('mate_clean', models.FloatField()),
                ('permission_to_enter', models.FloatField()),
                ('User', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, related_name='matching_info', to='matching.user')),
            ],
            options={
                'db_table': 'matching_info',
            },
        ),
    ]
