# Generated by Django 3.1.3 on 2021-11-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.IntegerField()),
                ('age', models.FloatField()),
                ('mbti', models.CharField(max_length=10)),
                ('user_smoking', models.IntegerField()),
                ('mate_smoking', models.FloatField()),
                ('user_pet', models.IntegerField()),
                ('user_pet_dog', models.IntegerField()),
                ('user_pet_cat', models.IntegerField()),
                ('user_pet_reptile_fish', models.IntegerField()),
                ('user_pet_rodent', models.IntegerField()),
                ('user_pet_bird', models.IntegerField()),
                ('mate_pet', models.FloatField()),
                ('mate_pet_dog', models.FloatField()),
                ('mate_pet_cat', models.FloatField()),
                ('mate_pet_reptile_fish', models.FloatField()),
                ('mate_pet_rodent', models.FloatField()),
                ('mate_pet_bird', models.FloatField()),
                ('air_like_airconditioner', models.IntegerField()),
                ('air_night_airconditioner', models.IntegerField()),
                ('air_like_heater', models.FloatField()),
                ('noise_talking', models.FloatField()),
                ('noise_music', models.FloatField()),
                ('noise_alarm', models.IntegerField()),
                ('user_bug_killer', models.FloatField()),
                ('mate_bug_killer', models.IntegerField()),
                ('user_cooking', models.IntegerField()),
                ('mate_cooking', models.IntegerField()),
                ('eat_together', models.IntegerField()),
                ('share_item', models.FloatField()),
                ('mate_alcohol', models.FloatField()),
                ('mate_clean', models.FloatField()),
                ('permission_to_enter', models.FloatField()),
            ],
            options={
                'db_table': 'matching_info',
                'managed': False,
            },
        ),
    ]
