# Generated by Django 3.1.3 on 2021-11-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchinginfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
