# Generated by Django 3.1.3 on 2021-11-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingResult',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('mate_uid', models.IntegerField()),
                ('update_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'matching_result',
                'managed': False,
            },
        ),
    ]
