# Generated by Django 3.1.3 on 2021-11-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_auto_20211120_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchinginfo',
            old_name='User',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='matchingresult',
            old_name='User',
            new_name='uid',
        ),
    ]
